name = "Test Packwiz"
author = "evylah"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "dea4ad6491b8dc02aadd181c81e44cd97fd4d9af7fc3c81017a22cb4bef02ae4"

[versions]
forge = "47.4.3"
minecraft = "1.20.1"

[options]
acceptable-game-versions = ["1.20.1"]
